//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomFreelance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Files1 = new HashSet<File>();
            this.Responses = new HashSet<Response>();
        }
    
        public int ID { get; set; }
        public int ID_Customer { get; set; }
        public int ID_Status { get; set; }
        public Nullable<int> ID_Executor { get; set; }
        public string Files { get; set; }
        public string Name { get; set; }
        public int ID_Subcategory { get; set; }
        public string Description { get; set; }
        public System.DateTime Deadline { get; set; }
        public decimal Budget { get; set; }
        public int ID_Place { get; set; }
        public string Address { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Executor Executor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files1 { get; set; }
        public virtual Place Place { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Response> Responses { get; set; }
    }
}
